### ISSUE TITLE
About the SqlQuote for DateTime<Utc> not implemented

### ISSUE THREAD

**Issue by litcc** [shanliu/sqlx-model#1]
![image](https://user-images.githubusercontent.com/13202561/210947237-eb376a24-fc97-4dec-8aa1-97ff11a52f96.png)

![image](https://user-images.githubusercontent.com/13202561/210947265-1c221b11-ed62-4f90-8b01-b2425e9dffde.png)

对于实现 SqlQuote  trait 是否有例子? 以及对于使用了sqlx:Type 宏的自定义类型 如何实现 SqlQuote trait

```
error[E0599]: no method named `sql_quote` found for reference `&chrono::DateTime<Utc>` in the current scope
  --> src/entity/sys_config.rs:15:39
   |
15 | #[derive(PartialEq, Debug, Clone, Eq, sqlx_model::SqlxModel)]
   |                                       ^^^^^^^^^^^^^^^^^^^^^ method not found in `&chrono::DateTime<Utc>`
   |
   = note: this error originates in the macro `$crate::model_table_ref_define` which comes from the expansion of the derive macro `sqlx_model::SqlxModel` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by litcc** [comment]
![image](https://user-images.githubusercontent.com/13202561/215452209-2113a979-b692-4786-857b-8603e3a1db86.png)
![image](https://user-images.githubusercontent.com/13202561/215452256-aae9837b-5b6f-478b-b236-6a93bc3128e5.png)
我fork后改动了点代码，最起码让我用的DateTime类型支持了，支持chrono里面其他结构应该问题不大

**Comment by shanliu** [comment]
如果只是sqlquote 实现 应该不会触发trait孤儿原则 晚上我试下

**Comment by shanliu** [comment]
impl<Tz: TimeZone> SqlQuote<String> for MyTime<Tz> 
其他类型根据自己需求实现即可以上trait即可
因为自定义的结构转成sql的值需要成如何我也不清楚。。。

**Comment by litcc** [comment]
好的，我尝试一下，谢谢

**Comment by shanliu** [comment]
> 好的，我尝试一下，谢谢

可行的话 帮忙关闭 issues～ 😊
